databases:
  - name: rails_practice
    databaseName: rails_practice
    user: rails_practice
    plan: free

services:
  - type: web
    plan: free
    name: rails_practice
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails_practice
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
